[package]
name = "kvs"
version = "0.1.0"
authors = ["Gilbert Röhrbein <gilbert@ifsr.de>"]
edition = "2018"

[lib]
doctest = false
test = false

[[bin]]
name = "kvs"
test = false

[dependencies]
clap = "2.33"

[dev-dependencies]
assert_cmd = "1.0"
predicates = "1.0"