[package]
name = "playground-kvs"
version = "0.1.0"
authors = ["Gilbert Röhrbein <gilbert@ifsr.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
