[package]
name = "ggez-kruemel"
version = "0.1.0"
authors = ["Gilbert Röhrbein"]
edition = "2018"
license = "AGPL3"

[dependencies]
rand = "0.7.3"
gfx = "0.18.2"
bitflags = "1.2.1"
palette = "0.5.0"
line_drawing = "0.8.0"

[dependencies.ggez]
version = "0.5.1"
default-features = false