on: [push]
defaults:
  run:
    shell: bash
jobs:
  cargo-build-and-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install libasound2-dev libudev-dev
      - run: cargo build --verbose
      - run: cargo test --verbose